### ISSUE TITLE
ability to view or convert BMP resources

### ISSUE THREAD

**Issue by madmuffin** [JohnGlassmyer/dsun_music#1]
I don't know enough about GIT to message you directly but I am using your tool to dump the contents of the dark sun GFFs. I installed apache maven and a JDK and used gfftool to extract the contents of a GFF into a folder, but the extracted contents have no file type, they are a long list like "bmp -0397". How do I turn this file into something I can view, assuming it really is a BMP?

**Comment by JohnGlassmyer** [comment]
"BMP" resources in Dark Sun are not the same format as Microsoft BMP files. You won't be able to open them in MS Paint. I did write some code at some point to display them on screen, but nothing fit for release. If I remember correctly, they use some form of run-length encoding. I don't remember now whether I reverse-engineered it by myself or read a description that someone had posted online.

What is your interest in extracting or viewing the images?

**Comment by madmuffin** [comment]
Thanks for the reply John! I was hoping to see what kind of assets made it into the game that were never used, stuff still in the repos that never show up in the game. Cutting room floor type content. Ravager is the game I fell in love with growing up that lead me into game development and it's still my favorite of all time, so just being able to see all the art assets laid out on the table is also a big driving factor for my interest.

**Comment by JohnGlassmyer** [comment]
I see. I think it's a neat idea, but I have no plans to spend time on this at the moment. If I were to approach it again, I might try disassembling the game executable with the freeware version of IDA Pro and looking at how it processes BMP resources.

**Comment by madmuffin** [comment]
Ahh alright John, thanks all the same. I am not confident I'll be able to figure it out on my own, I don't have much experience with reverse-engineering games sadly. I wish I could get my hands on what you did have to display them on screen, even if you feel its unfit to be published, but I respect if you aren't interested in releasing that.

**Comment by JohnGlassmyer** [comment]
My curiosity got the better of me, so I revisited my old code and finished reverse-engineering the format of those images. It turned out to be not much more complicated than I had already figured out.

I'll develop a command-line tool to export the images, probably as TIFFs as many of them contain multiple frames.

**Comment by madmuffin** [comment]
Wow, John that's fantastic! I am really excited to see what you pull off.

**Comment by JohnGlassmyer** [comment]
It's done. There's now an image-tool project that you can build and use to generate a TIFF for any of the BMP files. An animated BMP will convert to a multiple-page TIFF, which only a subset of software programs will recognize.

Note that I've changed the naming of the old projects and how resource files are numbered when exported, so I'd recommend deleting any old files you have lying around from the old version before updating and starting fresh.

**Comment by madmuffin** [comment]
Thanks again John! I tried it out, I was able to export all the DSUN GFF files, exported a multi-frame tiff and viewed multiple frames successfully as well. I hit a snag however when I attempted to export a region for viewing:
![extractingaregion](https://user-images.githubusercontent.com/908876/42920803-922e9c7e-8ae6-11e8-9a08-ab1d19c78ca8.PNG)
I looked it over a few times and couldn't see where I was making a mistake.

**Comment by JohnGlassmyer** [comment]
That exception on that line would imply that the RGN file did not contain an RMAP resource, which should not happen for RGNs from Dark Sun: Shattered Lands. I haven't paid much attention to Dark Sun 2 or Crimson Sands yet. They structure data somewhat differently.

**Comment by madmuffin** [comment]
Ahh I see. I extracted the Shattered Lands GFFs this time and the region export test worked flawlessly.

**Comment by madmuffin** [comment]
Hey John, over the last week using your tools I've successfully extracted as far as I can tell 100% of Shattered Lands' artwork, all the maps, characters, spells, even all the UI elements. There are even ICON files which export just as well as the BMP files into tiffs. 

Wake of the Ravager was a bit more rough. I extracted all the files and batch converted the whole thing, about 70% of them convert to blank transparent images that are the correct dimensions of their contents, but empty. 

Ravager does export successfully all the PC, NPC, and Monster sprites, some GUI and spell effects, and a few world props. From what did export, I found some interesting stuff already, like a joke loading screen and a completely nude base sprite they must have used as a template to make the various NPCs.

**Comment by JohnGlassmyer** [comment]
I'm glad you were able to find some things that you find interesting. I did not notice those bits you found in Dark Sun 2.

I've now added the ability to process images and regions from Dark Sun 2 and Crimson Sands, and fixed the region-tool to more accurately composite images. So you can go check out pirates on the high silt seas, if you have Crimson Sands files. Command line syntax has probably changed again.

**Comment by madmuffin** [comment]
I'm extremely excited to look at Crimson Sands's files. I've never played due to the whole servers thing it and this will be the first time ever taking a peek inside.
