### ISSUE TITLE
Am I doing this right?

### ISSUE THREAD

**Issue by Dark-Sun-DM** [JohnGlassmyer/dsun_music#2]
JohnGlassmyer,

My name is Jared and I have been a huge fan of the Dark Sun games since I was introduced to them back in the early 90s. I think I've played through them several dozen times since then. I recently started playing DnD through a virtual tabletop with my gaming group during the pandemic. I thought it would be great to do the Shattered Lands game as a full campaign. I found some of the map images online and things have been going smoothly. I realized that not all of the maps are available online. I own the game on GOG and I recently purchased a CD-ROM version but I quickly learned that getting usable image files is well beyond my knowledge area. I was pointed to your project by the RGB Classic Games forum (https://www.classicdosgames.com/forum/viewtopic.php?f=19&t=1788)

I realized I am still well outside my comfort area when I tried to setup JDK and Apache Maven. This is like a foreign language to me. My goal is to pull all of the regional maps and convert them to high res image files (jpeg/png/etc). I don't need any of the terrain triggers or music. Do you have any suggestions on where I could find help with my project?

This game means a lot to me. Any help you can provide would be most appreciated!

Sincerely,

Jared

I hope I am using git hub correctly. My apologies if I am not.

**Comment by JohnGlassmyer** [comment]
someone else running a D&D group wanted the images for the same purpose about a year and a half ago, so i rendered them and uploaded them to imgur back then:

https://imgur.com/a/X3cdql9

is that what you were looking for?

**Comment by Dark-Sun-DM** [comment]
Oh my god! YES! This is **exactly** what I was looking for. You just made my day/week/month/year! I appreciate this so much. Is there anything I can do for you?

**Comment by JohnGlassmyer** [comment]
nah, just spread the word of where you got the goodies.
