### ISSUE TITLE
Source of informations regarding file formats, aso... ?

### ISSUE THREAD

**Issue by snichele** [JohnGlassmyer/dsun_music#3]
Hi John,
After searching on the internet for a way to contact you, I decided to open an issue here... I hope you wouldn't mind !  ^_^

I was wondering where you found informations regarding the file formats ? I searched the net and didn't find any resource describing the file formats or whatever. Furthermore, in your source code, there is a reference to the darksun.exe file : did you decompiled it and studied the assembly code ?

I'm really interested in digging in the game resources, scripts, and such... for educational purpose (I'm a 'modern' developper myself and really interested in studying 'old school' ways of doing things back in the days, using my favourites games as a support - which is rather hard, considering the terrible lack of available source code ....)

I hope this message will reach you... ;)

**Comment by JohnGlassmyer** [comment]
yeah i used the very old freeware version of IDA (probably version 5.0, "Mar 31, 2018: IDA Disassembler" on the ScummVM website) to disassemble the executables. it gives you, for each procedure in the executable, something like a flow chart of blocks of assembly / machine instructions. i explored the disassembly until i found the procedure that processes or decompresses the file or image format, and stepped through to learn what it's doing. if i remember correctly, Dark Sun 2 added another type of image compression that wasn't in the first game. it's been several years and my memory is not precise.

**Comment by snichele** [comment]
Thanks john for the answer ! :)
But considering that assembly is really really low level (and the fact that the last time i programmed in assembly, it was 25 years agos... for a small assignement...), I wonder how someone can actually "understand something" out of all that register and memory values swap...
I tried IDA V5 on the executable, and frankly, it's daunting. I see the workflow you mentionned, but It will probably take me forever to understand something, even less recognize some image decompression...
Is there any guide to give newcomers some key principles for "decoding" assembly without a PHD or 20years of experience... :D

Ho, and I almost forgot : thank you so much for having made that effort and published your sources online, I'm a huge fan of the game and toying with resources extraction is a great fun ! :)

**Comment by JohnGlassmyer** [comment]
well, my investigations tended to be particularly or intensely motivated. i never got anywhere close to analyzing the entire executables. rather i would dig to find the one thing that annoyed me about the game or the one thing i wanted to understand about some file format or the other. and that one intense motivation would carry me through exploring and making sense of various procedures in the executable. i imagine it would be difficult to try to analyze and "figure out" the executable as a whole without any particular goal in mind.

if you're starting with a particular goal, then there are particular "ins" to old DOS game executables like these. you can search for the references to a particular hard coded string, or you can find the (rather large, in byte length) procedure that interprets the hard coded mapping of keyboard commands, and go from there.

**Comment by snichele** [comment]
A "high motivation" fueled quest, indeed ! :D 
Thank you so much for taking the time to clarify thoses points for me ! ;)
